# Generated by Django 3.1.5 on 2021-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210305_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
