# Generated by Django 3.1.5 on 2021-03-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210326_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('completed', 'Заказ выполнен'), ('in_ready', 'Заказ готов'), ('new', 'Новый заказ')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('screen_refresh_rate', models.CharField(max_length=255, verbose_name='Частота обновления экрана')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('sound_power', models.CharField(max_length=255, verbose_name='Мощность звука')),
                ('sd', models.BooleanField(default=True, verbose_name='Наличие SD карты')),
                ('extra', models.TextField(null=True, verbose_name='Дополнительно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
