# Generated by Django 3.1.5 on 2021-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210327_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_ready', 'Заказ готов'), ('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='watch_type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
    ]
