# Generated by Django 3.1.5 on 2021-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20210330_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке'), ('in_ready', 'Заказ готов')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='television',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
