# Generated by Django 3.1.5 on 2021-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210330_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('new', 'Новый заказ'), ('completed', 'Заказ выполнен'), ('in_ready', 'Заказ готов')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
